spring:
  application:
    name: @project.artifactId@
  profiles:
    active: @profiles.activation@

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: @eureka.address@

server:
  port: 8768

zuul:
  routes:
    customer:
      path: /customer/**
      serviceId: ihome-customer
    account:
      path: /account/**
      serviceId: ihome-account

#如果下游接口配置了熔断需要配置超时，要不有bug
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

#如果下游接口配置了熔断需要配置超时，要不有bug
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000