server:
  port: 8766

mybatis:
  mapper-locations: classpath*:mapper/*.xml

logging:
#  level.root: INFO
#  level.com.panjin: DEBUG
  path: /Users/panjin/logs/
#  config: classpath:logback-spring.xml
